import style from './styles/Home.module.css'
import { NextPage } from "next";
import React, { useEffect, useState } from "react";
import { Livro } from '../classes/modelo/Livro';
import Head from 'next/head';
import { Menu } from '../componentes/Menu';
import { LinhaLivro } from '../componentes/LinhaLivro';

const baseURL = "http://localhost:3000/api/livros";

const LivroLista: NextPage = () => {
  const [livros, setLivros] = useState<Array<Livro>>([])
  const [carregado, setCarregado] = useState<boolean>(false);

  const obterLivro = async () => {
    try {
      const response = await fetch(baseURL)
      const data = await response.json();
      setLivros(data.livros)
      console.log(data)
      setCarregado(true)
    } catch (error) {
      console.log('Erro ao obter livros: ', error)
    }
  }

  const excluirLivro = async (codigo: number) => {
    try {
      const response = await fetch(`${baseURL}/${codigo}`, {
        method: 'DELETE'
      })
      if (response.ok) {
        setCarregado(false)
      } else {
        console.log('Erro ao excluir livro: ', response.statusText)
      }
    } catch (error) {
      console.log("Erro ao excluir livro: ", error)
    }
  }

  useEffect(() => {
    obterLivro()
  }, [carregado])

  return (
    <div className={style.container}>
      <Head>
        <title>Loja Next</title> {/* Alterar o título para "Loja Next" */}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
      <main>
        <h1>Catálogo de Livros</h1>
        <table className="table table-striped table-hover">
          <thead className="table-dark">
            <tr>
              <th style={{ width: '16%' }}>Título</th>
              <th style={{ width: '50%' }}>Resumo</th>
              <th style={{ width: '16%' }}>Editora</th>
              <th style={{ width: '16%' }}>Autores</th>
            </tr>
          </thead>
          <tbody>
            {livros.map((livro) =>
              <LinhaLivro key={livro.codigo} livro={livro} excluir={excluirLivro} />
            )}
          </tbody>
        </table>
      </main>
    </div>
  )
}

export default LivroLista;